framework:
  secret: '%env(APP_SECRET)%'
  csrf_protection: true
  http_method_override: true
  session:
    cookie_lifetime: 172800
    gc_maxlifetime: 172800
  esi: true
  fragments: true
  php_errors:
    log: true
