security:
  password_hashers:
    App\Entity\User: 'auto'

  providers:
    app_user_provider:
      entity:
        class: App\Entity\User
        property: email

  firewalls:
    dev:
      pattern: ^/(_(profiler|wdt)|css|images|js)/
      security: false

    main:
      lazy: true
      provider: app_user_provider
      form_login:
        login_path: app_login
        check_path: app_login
        enable_csrf: true
        default_target_path: app_book_index
      logout:
        path: app_logout
      remember_me:
        secret: '%kernel.secret%'
        lifetime: 172800
        path: /

  access_control:
    - { path: ^/login, roles: PUBLIC_ACCESS }
    - { path: ^/register, roles: PUBLIC_ACCESS }
    - { path: ^/book, roles: ROLE_USER }
    - { path: ^/author, roles: ROLE_USER }
    - { path: ^/user, roles: ROLE_ADMIN }

when@test:
  security:
    password_hashers:
      App\Entity\User:
        algorithm: auto
        cost: 4
        time_cost: 3
        memory_cost: 10
